ci: temporarily disable githook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-make format
+# make format
 
-if [ $? -eq 0 ]; then
-    echo >&2 "Formatted successfully."
-else
-    echo >&2 "Error formatting."
-    exit 1
-fi
+# if [ $? -eq 0 ]; then
+#     echo >&2 "Formatted successfully."
+# else
+#     echo >&2 "Error formatting."
+#     exit 1
+# fi
